FROM node:20-slim

WORKDIR /usr/src/app
RUN apt-get update && \
    apt-get install -y openssl ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN npm config set strict-ssl false

RUN npx prisma generate && npm run build

EXPOSE 4000
ENV NODE_ENV=production
ENV PORT=4000

CMD ["sh", "-c", "if [ \"$NODE_ENV\" = 'development' ]; then npm run dev; else npm run start; fi"]
